'use client';

import React from "react";
import { Inter } from "next/font/google";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>ChatGPT - Login or Sign Up</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
};

export default RootLayout;
